{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "5d4d1c0e_e8ff34c7",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1076123
      },
      "writtenOn": "2022-03-17T00:42:18Z",
      "side": 1,
      "message": "I don\u0027t understand the failure mode, but we can revert and try again later.  The same tests pass for us on a different platform.",
      "revId": "2b0dd3bcbde08e8b51553ae37e1d8686bad53f0f",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    }
  ]
}