{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "e56dd279_3a7c7cf3",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 1002751
      },
      "writtenOn": "2021-01-29T18:12:47Z",
      "side": 1,
      "message": "Presubmit failure is:\n\nTraceback (most recent call last):\n  File \"/mnt/disks/build-disk/src/android/master/out/soong/.temp/Soong.python_ESln1U/extract_kernel.py\", line 263, in \u003cmodule\u003e\n    sys.exit(main())\n  File \"/mnt/disks/build-disk/src/android/master/out/soong/.temp/Soong.python_ESln1U/extract_kernel.py\", line 251, in main\n    if not dump_to_file(args.output_release, dump_release, input_bytes,\n  File \"/mnt/disks/build-disk/src/android/master/out/soong/.temp/Soong.python_ESln1U/extract_kernel.py\", line 180, in dump_to_file\n    f.write(o.encode())\nTypeError: write() argument must be str, not bytes\n",
      "revId": "de3a31a6f73d3005af0ee4faca24dc01b137ec4f",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "f26bce9a_a7612646",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 1121838
      },
      "writtenOn": "2021-01-29T19:28:25Z",
      "side": 1,
      "message": "yuyezhong@gmail.com Please fix this.",
      "parentUuid": "e56dd279_3a7c7cf3",
      "revId": "de3a31a6f73d3005af0ee4faca24dc01b137ec4f",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "01acbd74_aac651b4",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 1029303
      },
      "writtenOn": "2021-01-30T08:21:25Z",
      "side": 1,
      "message": "I can not reproduce the issue found by Treehugger, which is a little weird.\nI just modified the checking condition of encoding data for write().\n\nMore local Tests:\nextract info from Pixel 4 and Pixel 5 kernels,\nwith python versions: [2.7.18, 3.6.1, 3.8.1, 3.9.1].",
      "parentUuid": "f26bce9a_a7612646",
      "revId": "de3a31a6f73d3005af0ee4faca24dc01b137ec4f",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "a6b62a09_e82fac40",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 1121838
      },
      "writtenOn": "2021-02-01T20:23:38Z",
      "side": 1,
      "message": "Did you try --output-X with and without a file argument, both in Python 2 and 3?",
      "parentUuid": "01acbd74_aac651b4",
      "revId": "de3a31a6f73d3005af0ee4faca24dc01b137ec4f",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "c22706db_86632901",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 1121838
      },
      "writtenOn": "2021-02-02T01:49:20Z",
      "side": 1,
      "message": "The problem is not resolved. Maybe try:\n\n  lunch aosp_cf_x86_64_phone-userdebug\n  mmma packages/modules/Gki\n\nand see if you reproduce the error?",
      "parentUuid": "a6b62a09_e82fac40",
      "revId": "de3a31a6f73d3005af0ee4faca24dc01b137ec4f",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "ed78b827_5e9c2828",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 1029303
      },
      "writtenOn": "2021-02-05T05:43:01Z",
      "side": 1,
      "message": "Thanks, I can reproduce the issue with \"mmma packages/modules/Gki\".\nPatch Set 4 fixed the problem.",
      "parentUuid": "c22706db_86632901",
      "revId": "de3a31a6f73d3005af0ee4faca24dc01b137ec4f",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    }
  ]
}