{
  "comments": [
    {
      "key": {
        "uuid": "30ca486f_ec61a429",
        "filename": "tools/warn.py",
        "patchSetId": 1
      },
      "lineNbr": 747,
      "author": {
        "id": 1010118
      },
      "writtenOn": "2016-11-18T06:38:04Z",
      "side": 0,
      "message": "Is removing this a glitch?",
      "range": {
        "startLine": 743,
        "startChar": 0,
        "endLine": 747,
        "endChar": 57
      },
      "revId": "e4fb495b09cb919b6517c2ad7b8eea09c34d555d",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "f07c302f_2f836595",
        "filename": "tools/warn.py",
        "patchSetId": 1
      },
      "lineNbr": 747,
      "author": {
        "id": 1129817
      },
      "writtenOn": "2016-11-22T18:34:10Z",
      "side": 0,
      "message": "Moved to line 622. Looks like this got demoted to WARNING from ERROR in internal cl/122684354\n\nMaybe there are a few of these we might want to re-promote to SEVERE in the genscript?",
      "parentUuid": "30ca486f_ec61a429",
      "range": {
        "startLine": 743,
        "startChar": 0,
        "endLine": 747,
        "endChar": 57
      },
      "revId": "e4fb495b09cb919b6517c2ad7b8eea09c34d555d",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": false
    }
  ]
}