{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "131d2c8d_387d64ef",
        "filename": "tools/edit_monitor/daemon_manager.py",
        "patchSetId": 3
      },
      "lineNbr": 130,
      "author": {
        "id": 1132849
      },
      "writtenOn": "2024-12-06T23:11:06Z",
      "side": 1,
      "message": "will this ever throw error?",
      "range": {
        "startLine": 130,
        "startChar": 7,
        "endLine": 130,
        "endChar": 37
      },
      "revId": "ec657cedbb84e26540a0e062915bc53b6cb0caaf",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    }
  ]
}